apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - args:
          - "m"
          - "http.server"
          - "8080"
          image: westar.tencentcloudcr.com/bns/web:latest
          name: webapp
          command: ["python3"]
